project:
  type: website

website:
  title: "MCP Workshop July 2025"
  navbar: false
  page-navigation: true

format:
  revealjs:
    theme: default
    controls: true
    progress: true
    hash: true
    footer: "Conversational Interfaces for Research | <a href=\"https://cdi.nu\" target=\"_blank\">Cristian Dinu</a> | c.dinu@ucl.ac.uk"
    menu: true
    preview-links: true